import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Brain,
  Zap,
  Target,
  TrendingUp,
  CheckCircle,
  ArrowRight,
  Sparkles,
  BookOpen,
} from "lucide-react";
import useAuthStore from "../store/authStore";
import Button from "../components/common/Button";
import DemoSection from "../components/demo/DemoSection";

const Home = () => {
  const { isAuthenticated } = useAuthStore();

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Quiz Generation",
      description:
        "Upload your notes and get personalized quizzes instantly generated by advanced AI.",
    },
    {
      icon: Target,
      title: "Adaptive Learning",
      description:
        "Questions adjust to your performance level, ensuring optimal challenge and growth.",
    },
    {
      icon: TrendingUp,
      title: "Progress Tracking",
      description:
        "Monitor your improvement over time with detailed analytics and insights.",
    },
    {
      icon: Zap,
      title: "Instant Feedback",
      description:
        "Get immediate results with explanations to reinforce your learning.",
    },
  ];

  const testimonials = [
    {
      name: "Sarah Johnson",
      grade: "11th Grade",
      text: "This app helped me improve my test scores by 30%! The AI really understands what I need to work on.",
      avatar: "SJ",
    },
    {
      name: "Alex Chen",
      grade: "12th Grade",
      text: "I love how it creates quizzes from my own notes. It feels like having a personal tutor.",
      avatar: "AC",
    },
    {
      name: "Emma Wilson",
      grade: "10th Grade",
      text: "The progress tracking keeps me motivated. I can see myself getting better every week!",
      avatar: "EW",
    },
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="hero-gradient text-white section-padding">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="flex justify-center mb-6">
              <motion.div
                whileHover={{ rotate: 20, scale: 1.1 }}
                className="w-20 h-20 bg-white/20 rounded-2xl flex items-center justify-center backdrop-blur-sm"
              >
                <Brain size={40} />
              </motion.div>
            </div>

            <h1 className="text-5xl md:text-6xl font-bold font-display mb-6">
              AI Exam Readiness Checker
            </h1>

            {/* Motivational Tagline */}
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4, duration: 0.5 }}
              className="mb-6"
            >
              <p className="text-2xl font-semibold text-yellow-200 font-display italic">
                "Study Smarter, Not Harder"
              </p>
            </motion.div>

            <p className="text-xl mb-8 text-white/90 max-w-2xl mx-auto">
              Turn your study notes into personalized AI quizzes. Get instant
              feedback, track your progress, and improve your exam readiness.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              {isAuthenticated ? (
                <Link
                  to="/dashboard"
                  className="btn bg-white text-primary-600 hover:bg-gray-100 btn-lg"
                >
                  Go to Dashboard
                  <ArrowRight size={20} className="ml-2" />
                </Link>
              ) : (
                <>
                  <Link
                    to="/register"
                    className="btn bg-white text-primary-600 hover:bg-gray-100 btn-lg"
                  >
                    Get Started Free
                    <ArrowRight size={20} className="ml-2" />
                  </Link>
                  <Link
                    to="/login"
                    className="btn border-2 border-white text-white hover:bg-white hover:text-primary-600 btn-lg"
                  >
                    Sign In
                  </Link>
                </>
              )}
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="section-padding bg-white">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold text-gray-900 font-display mb-4">
              Powerful Features for Better Learning
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Discover how our AI-powered platform makes studying more effective
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={feature.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="card card-hover text-center"
                >
                  <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center mx-auto mb-4">
                    <Icon size={24} className="text-primary-600" />
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600">{feature.description}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Demo Section */}
      <DemoSection />

      {/* Testimonials Section */}
      <section className="section-padding bg-white">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold text-gray-900 font-display mb-4">
              What Students Are Saying
            </h2>
            <p className="text-xl text-gray-600">
              Real success stories from real students
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <motion.div
                key={testimonial.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="card"
              >
                <div className="flex items-center mb-4">
                  <div className="w-12 h-12 bg-primary-600 rounded-full flex items-center justify-center text-white font-medium mr-4">
                    {testimonial.avatar}
                  </div>
                  <div>
                    <div className="font-semibold text-gray-900">
                      {testimonial.name}
                    </div>
                    <div className="text-sm text-gray-600">
                      {testimonial.grade}
                    </div>
                  </div>
                </div>
                <p className="text-gray-700 italic">"{testimonial.text}"</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Topic Showcase Section */}
      <section className="section-padding bg-gradient-to-br from-gray-50 to-blue-50">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-gray-900 font-display mb-4">
              🤖 Smart Topic Detection
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our AI automatically identifies your subject and generates
              topic-specific questions
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                topic: "Mathematics",
                displayName: "Calculus",
                icon: "📐",
                color: "from-blue-100 to-blue-200",
                textColor: "text-blue-800",
              },
              {
                topic: "Biology",
                displayName: "Biology",
                icon: "🧬",
                color: "from-green-100 to-green-200",
                textColor: "text-green-800",
              },
              {
                topic: "Chemistry",
                displayName: "Chemistry",
                icon: "⚗️",
                color: "from-purple-100 to-purple-200",
                textColor: "text-purple-800",
              },
            ].map((item, index) => (
              <Link
                key={item.topic}
                to={`/browse?category=${item.topic}`}
                className="block"
              >
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.2 }}
                  className={`bg-gradient-to-br ${item.color} rounded-xl p-6 text-center hover:scale-105 transition-transform duration-200 cursor-pointer`}
                >
                  <div className="text-4xl mb-3">{item.icon}</div>
                  <h3
                    className={`text-xl font-semibold ${item.textColor} mb-2`}
                  >
                    {item.displayName}
                  </h3>
                  <p className={`text-sm ${item.textColor}/80`}>
                    AI detects and creates {item.displayName.toLowerCase()}
                    -specific questions
                  </p>
                </motion.div>
              </Link>
            ))}
          </div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.8 }}
            className="text-center mt-8"
          >
            <p className="text-gray-600 mb-6">
              + Many more subjects: Physics, History, Economics, Psychology, and
              more!
            </p>
            <Link to="/browse">
              <Button variant="outline" size="lg">
                Browse All Quizzes
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="hero-gradient text-white section-padding">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl font-bold font-display mb-6">
              Start Using AI Exam Readiness Checker
            </h2>
            <p className="text-xl mb-8 text-white/90 max-w-2xl mx-auto">
              Create your account and begin generating AI-powered quizzes from
              your study materials
            </p>

            {!isAuthenticated && (
              <Link
                to="/register"
                className="btn bg-white text-primary-600 hover:bg-gray-100 btn-lg"
              >
                Get Started
                <ArrowRight size={20} className="ml-2" />
              </Link>
            )}
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default Home;
