import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Play, Clock, BookOpen, Brain } from "lucide-react";
import Button from "../common/Button";
import { getDifficultyColor } from "../../utils/helpers";

const DemoQuizCard = ({ quiz, index = 0 }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.1 }}
      className="card card-hover group relative overflow-hidden"
    >
      {/* Demo Badge */}
      <div className="absolute top-4 right-4 z-10">
        <span className="badge bg-gradient-to-r from-purple-500 to-pink-500 text-white font-medium">
          ✨ Demo
        </span>
      </div>

      {/* Background Gradient */}
      <div className="absolute inset-0 bg-gradient-to-br from-primary-50 to-secondary-50 opacity-50" />

      <div className="relative z-10">
        {/* Header */}
        <div className="flex items-start justify-between mb-4">
          <div className="flex-1">
            <h3 className="text-xl font-semibold text-gray-900 mb-2 group-hover:text-primary-600 transition-colors">
              {quiz.title}
            </h3>
            <div className="flex items-center space-x-2 text-sm text-gray-600 mb-3">
              <BookOpen size={16} />
              <span>{quiz.subject}</span>
              <span>•</span>
              <Clock size={16} />
              <span>
                {quiz.questions?.length || quiz.totalQuestions} questions
              </span>
            </div>
          </div>
          <span className={`badge ${getDifficultyColor(quiz.difficulty)}`}>
            {quiz.difficulty}
          </span>
        </div>

        {/* Description */}
        <p className="text-gray-600 mb-6 line-clamp-2">
          {quiz.description ||
            "Experience AI-powered quiz generation with this sample quiz."}
        </p>

        {/* Stats Grid */}
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="text-center p-3 bg-white/50 rounded-lg">
            <div className="text-lg font-semibold text-primary-600">
              {quiz.timeLimit || "∞"}
            </div>
            <div className="text-xs text-gray-600">
              {quiz.timeLimit ? "Minutes" : "No limit"}
            </div>
          </div>
          <div className="text-center p-3 bg-white/50 rounded-lg">
            <div className="text-lg font-semibold text-success-600">AI</div>
            <div className="text-xs text-gray-600">Generated</div>
          </div>
          <div className="text-center p-3 bg-white/50 rounded-lg">
            <div className="text-lg font-semibold text-warning-600">Live</div>
            <div className="text-xs text-gray-600">Feedback</div>
          </div>
        </div>

        {/* Sample Topics */}
        {quiz.questions && (
          <div className="mb-6">
            <h4 className="text-sm font-medium text-gray-700 mb-2">
              Sample Topics:
            </h4>
            <div className="flex flex-wrap gap-2">
              {Array.from(
                new Set(quiz.questions.map((q) => q.topic).filter(Boolean))
              )
                .slice(0, 3)
                .map((topic) => (
                  <span key={topic} className="badge badge-primary text-xs">
                    {topic}
                  </span>
                ))}
            </div>
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex items-center space-x-3">
          <Link to={`/quiz/${quiz._id}`} className="flex-1">
            <Button className="w-full group-hover:scale-105 transition-transform">
              <Play className="mr-2" size={16} />
              Try Demo Quiz
            </Button>
          </Link>
          <motion.button
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            className="w-12 h-12 rounded-lg bg-gradient-to-r from-primary-100 to-secondary-100 flex items-center justify-center text-primary-600 hover:from-primary-200 hover:to-secondary-200 transition-all"
            title="View Details"
          >
            <Brain size={20} />
          </motion.button>
        </div>

        {/* Fun Fact */}
        <div className="mt-4 p-3 bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg border border-blue-100">
          <div className="flex items-center space-x-2">
            <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse"></div>
            <span className="text-sm text-blue-700 font-medium">
              This quiz was generated by AI in under 30 seconds! 🚀
            </span>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default DemoQuizCard;
